const routers = require("express").Router();
const castsRoutes = require("./casts");
const genresRoutes = require("./genres");
const moviesRoutes = require("./movies");
const rolesRoutes = require("./roles");
const usersRoutes = require("./users");
const statusRoutes = require("./status");
const subscribersRoutes = require("./subscribers");
const movieCastRoutes = require("./movieCast");
const movieGenreRoutes = require("./movieGenre");
const movieScheduleTimesRoutes = require("./movieScheduleTimes");
const paymentMethodsRoutes = require("./paymentMethods");
const reserveSeatsRoutes = require("./reserveSeats");
const resetPasswordRoutes = require("./resetPassword");
const cinemasRoutes = require("./cinemas");
const movieSchedulesRoutes = require("./movieSchedules");
const transactionsRoutes = require("./transactions");

routers.use("/movies", moviesRoutes);
routers.use("/users", usersRoutes);
routers.use("/genres", genresRoutes);
routers.use("/roles", rolesRoutes);
routers.use("/casts", castsRoutes);
routers.use("/status", statusRoutes);
routers.use("/subscribers", subscribersRoutes);
routers.use("/movieCast", movieCastRoutes);
routers.use("/movieGenre", movieGenreRoutes);
routers.use("/movieScheduleTimes", movieScheduleTimesRoutes);
routers.use("/paymentMethods", paymentMethodsRoutes);
routers.use("/reserveSeats", reserveSeatsRoutes);
routers.use("/resetPassword", resetPasswordRoutes);
routers.use("/cinemas", cinemasRoutes);
routers.use("/movieSchedules", movieSchedulesRoutes);
routers.use("/transactions", transactionsRoutes);

module.exports = routers;
